name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install depends
      run: sudo apt-get install -y gcc-multilib pkg-config m4 libelf-dev libpcap-dev

    - name: Pull submodule
      run: git submodule update

    - name: Run make
      run: make

