name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install depends
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib pkg-config m4 libelf-dev libpcap-dev clang llvm \
          linux-tools-common linux-tools-generic
        sudo ln -sf /usr/lib/linux-tools/*-generic/bpftool /usr/local/bin/bpftool

    - name: Pull submodule
      run: git submodule init; git submodule update

    - name: Run make
      run: make

